import "./App.css";
import InfoSection from "./components/InfoSection";
import Carousel from "nuka-carousel";
import image1 from "./images/moonlight.png";
import image2 from "./images/personal-memories.png";
import image3 from "./images/relaxation.png";
import image4 from "./images/stress.png";
import image5 from "./images/therapy.png";
import image6 from "./images/fear-dread-pain.png";
import image7 from "./images/horror.png";
import { Link } from "react-router-dom";

function App() {
  return (
    <div className="landing-page">
      <div className="landing-page-button-container">
        <Link style={{textDecoration:"None"}} to="/about">
          <button className="landing-page-button-container__button">
            About
          </button>
        </Link>
        
      </div>
      <Carousel>
        <InfoSection
          source={image1}
          description="Participants from a group were told to look at two paintings by the artist Sighard Gille - one symbolizing life, the other symbolizing death. The painting above - depicting dark blue elders withering was decided by the group to reflect Beethoven’s Moonlight Sonata. (Martinez, 2013)"

          audio="https://upload.wikimedia.org/wikipedia/commons/1/14/Moonlight_Sonata_Movement_4.wav"
        />
        <InfoSection
          source={image2}
          description="Beethoven's 9th Symphony arouses personal memories, according to the same study by Martinez. For this image, we decided to use Wombo.ai to use AI to generate an image representing the emotion of nostalgia and personal memories."
          audio="https://upload.wikimedia.org/wikipedia/commons/0/06/Beethoven_symphony_no._9%2C_IV._Presto.flac"
        />
        <InfoSection
          source={image3}
          description='According to research done by Klaudia Krawczyk, Egmont Overture draws out a "low intensity" feeling of relaxation from the listener (Krawczyk, 2019). The above image was generated by Wombo.ai with the input "relaxation."'
          audio="https://upload.wikimedia.org/wikipedia/commons/2/20/Beethoven_EgmontOvertureOp.84_LudwigVanBeethoven-EgmontOvertureOp.84.ogg"
        />
        <InfoSection
          source={image4}
          description={`Krawczyk also notes that some of Beethoven's later works were at a point in his life where he was more stressed - which was often reflected in his works. The audio above is Beethoven's String Quartet No. 14. The image above was generated by Wombo.ai with the input "stress."`}
          audio="https://upload.wikimedia.org/wikipedia/commons/b/b9/Beethoven_String_Quartet_no._14%2C_V.Presto.oga"
        />
        <InfoSection source={image5} description={`Krawczyk states in her research - citing music therapist Elżbieta Galińska that Beethoven's "Apassionata" can be used during therapy to calm the patient (Krawczyk, 2019). The above image was generated by Wombo.ai using the prompt "therapy."`} audio="https://upload.wikimedia.org/wikipedia/commons/2/2c/Klaviersonate_Nr._23_f-moll_op._57_Appassionata_-_II._Andante_con_moto.oga" />
        <InfoSection source={image6} description={`"Fear, dread, and horror" are the emotions used to describe Beethoven's 5th Symphony in Wayne Senner's research regarding Beethoven's reception by his conteporaries (Senner, 2001). The audio above is the 5th Symphony in C minor Op 67. The image above was generated by Wombo.ai with the prompt fear/dread/horror`} audio="https://upload.wikimedia.org/wikipedia/commons/4/47/Ludwig_van_Beethoven_-_symphony_no._5_in_c_minor%2C_op._67_-_iv._allegro.ogg" />
      </Carousel>
    </div>
  )
}
export default App;
